### ISSUE TITLE
Scrolling up and down the scroll bar really quick freeze Visual Studio 2017 

### ISSUE THREAD

**Issue by prnadago** [microsoft/VS-ColorThemes#1]
video repro -> https://youtu.be/GZuBC_5wr9w
Noticeable things:
-Scrolling up and down the scroll bar really quick freeze visual studio
-If scrolled slowly the scroll bar shrinks, as if it is re-calculating its size based on how far we went down the list.

**Comment by Newrad0603** [comment]
This should be logged against the Color Theme Editor extension
