### ISSUE TITLE
Choosing Tools>Customize Colors crashes VS 2017

### ISSUE THREAD

**Issue by NateDev100** [microsoft/VS-ColorThemes#10]
Fresh VS 2017 install with the Color themes extension installed. When you go to Tools at the top, and then Color Themes, Visual Studio crashes and then restarts. Happens each time, whether you're on the Start page or a solution is open.

**Comment by justcla** [comment]
Can you please confirm which extension you installed?
- [Color Theme Editor for Visual Studio 2017](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.VisualStudio2017ColorThemeEditor)
- [Color Themes for for Visual Studio](https://marketplace.visualstudio.com/items?itemName=JustinClareburtMSFT.ColorThemesforVisualStudio)
You can check in Tools->Extensions and Updates

**Comment by NateDev100** [comment]
The first one, with 2017 in the name.

On Oct 18, 2017 12:04 PM, "Justin Clareburt" <notifications@github.com>
wrote:

Can you please confirm which extension you installed?

   - Color Theme Editor for Visual Studio 2017
   <https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.VisualStudio2017ColorThemeEditor>
   - Color Themes for for Visual Studio
   <https://marketplace.visualstudio.com/items?itemName=JustinClareburtMSFT.ColorThemesforVisualStudio>
   You can check in Tools->Extensions and Updates

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/VS-ColorThemes/issues/10#issuecomment-337641867>,
or mute the thread

**Comment by justcla** [comment]
Thanks

**Comment by NateDev100** [comment]
If it matters I installed a bit of an older version of VS, version 15.2 (26430.6)

**Comment by justcla** [comment]
Maybe something is corrupted with your installation. I recommend you upgrade to the latest public version. (Since VS2017, upgrades have become much smaller, faster and more reliable. So it's become much easier to keep up-to-date with the latest release.)
Failing that, I would consider completely uninstalling and reinstalling Visual Studio. (Again, this should not take too long. You'll just need to download and reinstall all your favourite extensions. You might also find them in the "Roaming Extensions" list in Tools->Extensions and Updates.

Hope that helps. Please let me know if you have success.

**Comment by NateDev100** [comment]
Would love to update to the latest version, but even though I selected my
other HDD, VS still installs most of the program on my C drive, which is an
SSD and I don't have enough space! I've got around 2TB on my other HDD but
nooo, we can't install Visual Studio there, we need to install it on your C
drive, even though you have limited space.



On Oct 18, 2017 5:09 PM, "Justin Clareburt" <notifications@github.com>
wrote:

Maybe something is corrupted with your installation. I recommend you
upgrade to the latest public version. (Since VS2017, upgrades have become
much smaller, faster and more reliable. So it's become much easier to keep
up-to-date with the latest release.)
Failing that, I would consider completely uninstalling and reinstalling
Visual Studio. (Again, this should not take too long. You'll just need to
download and reinstall all your favourite extensions. You might also find
them in the "Roaming Extensions" list in Tools->Extensions and Updates.

Hope that helps. Please let me know if you have success.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/VS-ColorThemes/issues/10#issuecomment-337728638>,
or mute the thread

**Comment by NateDev100** [comment]
What's sad is VS installer tells me I need 14GB to complete the update but I don't have enough space, and to try selecting another drive. I've already done that! But apparently even though the updates have gotten much smaller, it needs 14GB on my C drive and then even more on my other HDD...

**Comment by justcla** [comment]
That sounds like a terrible experience.
I will bring it up with the team.

**Comment by justcla** [comment]
Hi Nate

I've spoken to the team, and here's the information I've been given:

> Visual Studio itself installs to the drive you select, but a lot of the payload of VS is other stuff – SDKs, emulators, runtimes – and a lot of that installs into the %ProgramFiles% folder. It’s not ideal, and there are plans to fix it but it keeps being bumped down the backlog because it’s an expensive / risky change. 

> There are some other possibilities available – including manually moving the ‘package cache’ to another drive. 

> Probably the best bet is to go to our new Gitter channel at [https://gitter.im/Microsoft/VisualStudio](https://gitter.im/Microsoft/VisualStudio) - because that will make it easy for you to engage with us.

**Comment by dgriffen** [comment]
@NateDev100 are you able to run repair on your installation without filling up your hard drive? I just tested your scenario on the same build of VS that you have and I cannot reproduce the issue. I agree with @justcla that it is likely something corrupted with your installation.

**Comment by NateDev100** [comment]
Unfortunately not, I don’t have enough space even to repair the install, but for now I’ve just gone without the color themes until I can free up space or buy a new SSD 😊

Sent from Mail for Windows 10

**Comment by Newrad0603** [comment]
This should be logged against the Color Theme Editor extension
