### ISSUE TITLE
It is not clear how to use this plugin.

### ISSUE THREAD

**Issue by uglycoyote** [Microsoft/VS-ColorThemes#11]
I have install this plugin from within Visual Studio. When I installed the extension I did not see any obvious new menu entries (though there are many things in the menu so I might have missed it) and I also could not find anything new in the options page (again, hard to know if I missed it).  The "more information" link in the "Extensions and Updates" window took me to this github page.  However, the readme file in this repo only tells me how to contribute to the project but says nothing about how to actually use this extension.  

It would be very nice if there were some instructions.

**Comment by justcla** [comment]
Thanks for the suggestion about providing more info on how to use the extension.

To use the extension, simply click on one of the new themes, from the Color Theme picker page, from the Tools->Change Color Theme menu, or from the Color Theme dropdown in Tools->Options.

If the extension installed properly, then the next time you start Visual Studio, the Color Theme picker page should open in the document well.
There should be new items in the Color Theme drop-down in Tools->Options;Environment->General. You should see an additional eight themes.
There should be two new items on the Tools menu: Change Color Theme, and Customize Colors.
If these are not there, try re-installing the extension.

**Comment by prnadago** [comment]
It also depends on if you've installed the 'Color Theme Editor' in which you can 'Customize Colors', or just the 'Color Themes' in which you can only pick from the available color themes as found in this GitHub repo.

**Comment by amputek** [comment]
@prnadago Thank you! I never realised there was a distinction between the two extensions. I was stuck trying to work out why there was no 'Customize Colors' menu option  :)

**Comment by uglycoyote** [comment]
Thanks for the information.  The Color Theme Picker page did not show up when I restarted VS after installing this package, and I don't know how to get to the Color Theme Picker page.  Tools menu does not have a "Change Color Theme" option, and Tools->Options does not have any color theme options at the top level.  

Tools->Options->Environment->General does appear to have a few new schemes that probably were not there before, so I think those work correctly.

It's also still not clear to me whether this package is for choosing syntax highlighting color schemes,  or color schemes for the overall GUI, or both, and whether it's possible to choose those things independently.  I was really just looking for a way to browse syntax highlighting color schemes.

**Comment by prnadago** [comment]
Yes you are correct. This 'Color Themes' extension is only for installing additional color themes. They apply to all of the Visual Studio IDE and its components. You'll be able to choose between themes at Tools->Options->Environment->General.

If you would like to edit the existing themes, then you can install the Color Theme Editor extension by searching for it in Tools->Extensions and Updates. Doing this will give you the Tools menu options of 'Customize Colors' and 'Change Color Theme'.

Hope this makes things clear!

**Comment by uglycoyote** [comment]
Maybe my question was not clear, you are saying i'm correct but I was really asking a question and don't know what I'm correct about.  It seems like the language we are using is not clear.

A "Color Theme" is could be
- A set of colors for Visual Studio window components
- A set of colors for Code syntax Highlighting 


When reading about this add-in it is not clear which of those it controls, or if it affects both of those whether it allows me to change one independently of the other?

I'm currently fine with the default "dark" window component colours but was looking for something that would allow me to browse different syntax highlighting color schemes.

**Comment by prnadago** [comment]
Oh my bad sorry for the misunderstanding. To answer your question, a color theme affects both the window components and syntax highlighting. Right now by design, both of these aspects are married together in each color theme, and you cannot browse and pick syntax highlighting color schemes independent of the overall theme it comes packaged with.

If you would like to play around with syntax highlighting colors yourself, you can do that via the Color Theme Editor extension. It allows you to create a custom theme based on an existing theme and, for example, search for C++ and edit the colors for keywords, variables and other elements.

![image](https://user-images.githubusercontent.com/30607258/32016510-0634f5ea-b979-11e7-92f4-00173fb38c7f.png)

**Comment by uglycoyote** [comment]
excellent, thanks!
