### ISSUE TITLE
Issue copying Dark theme: function names turn from white to black

### ISSUE THREAD

**Issue by justcla** [microsoft/VS-ColorThemes#15]
User "Cracklings 3D" raised issue on Marketplace Ratings & Reviews:

> As soon as I copy the dark theme over (as a starting template), the function names (c++) turn from white to black. Literally just copied the setting, nothing changed yet. And the identifiers don't react to the font adjustments in settings anymore in any way. Wasted a whole evening for this, guess I'll stick to the default grey.

**Comment by Cracklings** [comment]
Did a repair with the installer and was able to identify the problem. Resharper is causing this strange behavior. Not sure why.
Thanks for opening this issue.

**Comment by JunielKatarn** [comment]
I encounter this issue too.
Is there a workaround?
![image](https://user-images.githubusercontent.com/4507319/47393082-6114d980-d6d3-11e8-9083-250d25fc08da.png)

**Comment by Newrad0603** [comment]
Appears related to Reshaper, so closing this issue.
