### ISSUE TITLE
Unexpected error while importing theme: System.Xml.XmlException 

### ISSUE THREAD

**Issue by enemymaker** [Microsoft/VS-ColorThemes#18]
When I want to import _any_ theme in Visual studio 2017, I get an XmlException error:

> ---------------------------
> Microsoft Visual Studio
> ---------------------------
> Unexpected error while importing theme: System.Xml.XmlException: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.
> 
>    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
>    at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
>    at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
>    at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
>    at System.Xml.XmlTextReaderImpl.Read()
>    at System.Xml.XsdValidatingReader.Read()
>    at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
>    at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
>    at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
>    at System.Xml.XmlDocument.Load(XmlReader reader)
>    at Microsoft.VisualStudio.Themes.Data.RegistryThemeIO.ReadThemeTemplatesFromXmlStream(Stream stream)
>    at Microsoft.VisualStudio.Themes.Designer.CommandHandlers.ImportTheme(ColorManager manager)
> 

The odd thing is that this happens as well with Visual Studio 2015 and any VS2015 theme, even themes I once have been able to import without any problems. 

Do you have any idea/clue on what's wrong?

Any hints are highly appreciated.

Cheers
Daniel

**Comment by justcla** [comment]
Hmmm.... That's strange. I'll ask around the office and see if anyone has some idea why this is happening for you now.

**Comment by justcla** [comment]
Sadly, many staff are on holidays, so we might not get a good response until next year.

**Comment by lorentzfb** [comment]
I got this error too. The file I downloaded was corrupt. 

Soulution for me: Open the raw file > Copy the content to notepad > Save as *.vstheme

**Comment by enemymaker** [comment]
Thanks for the hint.
I took a closer look at the downloaded file and it was indeed kind of corrupted.
After downloading it again, I did copy its content into notepad and saved it as new file. And then it worked.
