### ISSUE TITLE
Extension keeps losing the custom theme I have

### ISSUE THREAD

**Issue by CoolDadTx** [microsoft/VS-ColorThemes#23]
I am using a custom theme. Rather frequently I will restart VS 15.6 and the theme gets reset. When I go to switch it back the theme is gone. I import the theme again. Because of another issue the theme doesn't show up and you have to restart VS. The theme is then applied correctly. 

Some things that may be cause it to lose the theme.
1) I uninstall and/or install an extension in VS. Doesn't matter what that extension is.
2) Starting multiple instances of VS. Note that would all use the same theme but that doesn't seem to matter.
3) Using different instances of VS 2017 (I have both 15.5.4 and 15.6 preview installed. 

I cannot really identify the trigger state but it happens several times a week (and sometimes a day).

**Comment by justcla** [comment]
Thanks for letting us know. We'll look into it.

**Comment by prnadago** [comment]
@CoolDadTx Hi can you please use the Report a Problem tool within Visual Studio for this issue? It would be great if you could reproduce the issue and send files from the following locations:
1) %temp%/servicehub/logs
2) %localappdata%\microsoft\visualstudio\vshub
3) %localappdata%\microsoft\visualstudio\settingslogs
The engineering team will get it and take a look directly.

Thanks!

**Comment by CoolDadTx** [comment]
Added - https://developercommunity.visualstudio.com/content/problem/196406/color-theme-extension-keeps-losing-the-custom-them.html

**Comment by Newrad0603** [comment]
This should be (and was) filed against VS.
