### ISSUE TITLE
Question: Where can I find more themes?

### ISSUE THREAD

**Issue by adabo** [Microsoft/VS-ColorThemes#25]
Are there any more themes other than the the ones bundled in the extension? Or a website dedicated to them like [studiostyl.es](https://studiostyl.es/) or [vimcolors.com](http://vimcolors.com/)

**Comment by webmilio** [comment]
I second this question.

**Comment by justcla** [comment]
Not that I'm aware of. That's why I created this repo. I propose that this repo (and the resultant extension) contain a collection of user-contributed themes.
