### ISSUE TITLE
VS Marketplace hyperlink not working

### ISSUE THREAD

**Issue by GregTrevellick** [Microsoft/VS-ColorThemes#29]
The link to Color Theme Editor (https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.VisualStudio2017ColorThemeEditor) in the VS Marketplace site (https://marketplace.visualstudio.com/items?itemName=JustinClareburtMSFT.ColorThemesforVisualStudio) is broken.

So this isn't a bug as such, just minor cosmetic issue with the VS Marketplace text.
![jc0](https://user-images.githubusercontent.com/13434709/39481945-1bcf07ee-4d65-11e8-9d79-90bbf5feadab.PNG)
![jc](https://user-images.githubusercontent.com/13434709/39481948-1e6d48a8-4d65-11e8-89f7-9c938be064fa.PNG)

**Comment by justcla** [comment]
Fixed. Thanks very much.
