### ISSUE TITLE
Sublime Material Theme not working

### ISSUE THREAD

**Issue by garciaErick** [Microsoft/VS-ColorThemes#30]
I am trying to import this theme but since it is an xml I am unsure what to do... I just renamed the file to a .vstheme and imported it... however it does not change the look, what I am looking forward to is something similar to this, I am amazed nobody has done it for VS IDE
https://github.com/equinusocio/material-theme

**Comment by justcla** [comment]
The Sublime Material theme is available in my themes pack: [VS Color Themes](https://marketplace.visualstudio.com/items?itemName=JustinClareburtMSFT.ColorThemesforVisualStudio).

If you install the extension, you'll have the Sublime Material theme available.
You can change to it choosing the right theme in Tools->Options; Environment->General;Color Theme.

**Comment by justcla** [comment]
Also, I note that the link you provided is for a theme that was written for Sublime - not Visual Studio. So I'm not surprised it won't load in VS. That's like trying to open an Excel file in Word. :-)

**Comment by garciaErick** [comment]
Dude thanks :^) I just want my VS IDE to look as pretty as IntelliJ :^( ... thanks a lot, I wonder why its so hard to not make VS look like VS haha 

the theme looks sweet,

**Comment by garciaErick** [comment]
FYI of course its a sublime theme lol, I think you just misunderstood me. I was just trying to import the xml in your repo, not the one from the link I posted. I was just emphasizing that nobody had made that theme yet, and a lot of people like it

**Comment by justcla** [comment]
My bad. Actually, that's what I thought you meant at first. :-)

Glad you found and installed the Sublime Material theme. Happy days! :-D
You might want to write a note in the review section to give credit to the community memner who contributed it.

Closing the ticket.
