### ISSUE TITLE
When will the marketplace's version of color themes for visual studio be updated?

### ISSUE THREAD

**Issue by revosw** [Microsoft/VS-ColorThemes#33]
Just wanted to check in and ask how the progress is going for rolling out my updated theme?

**Comment by justcla** [comment]
Thanks for the heads up. I'll try to get onto it this week.

**Comment by justcla** [comment]
OK - I'm doing it now.

**Comment by justcla** [comment]
The updated Material Dark theme is now available on in the [Color Themes extension](https://marketplace.visualstudio.com/items?itemName=JustinClareburtMSFT.ColorThemesforVisualStudio) on the Marketplace in version 1.0.7.
