### ISSUE TITLE
Is there any theme gallery?

### ISSUE THREAD

**Issue by SuperJMN** [Microsoft/VS-ColorThemes#52]
Creating a theme can be difficult. Is there any gallery to download more themes?

I would like one based on VS 2010 :)

**Comment by justcla** [comment]
This is that gallery. :-)

The themes are here: https://github.com/Microsoft/VS-ColorThemes/tree/master/VSColorThemes/Themes

**Comment by SuperJMN** [comment]
Oh, thanks! I thought they would count by tenths, but there are only a bunch :) I hope this changes soon!

**Comment by justcla** [comment]
Actually, there are several PRs waiting to be accepted.
People add more themes every day, but I'm not keeping up with the PRs.

Definitely look for help here. :-D

**Comment by SuperJMN** [comment]
OK! I'll take a look. For now, I've seen that the extension expects .vstheme and .pkgdef files, but there are .xml files in the Themes folder.

**Comment by SuperJMN** [comment]
Found it that renaming to .vstheme does the trick :)
