### ISSUE TITLE
Error when using theme editor on VS2019 16.0-preview-3

### ISSUE THREAD

**Issue by EdCharbeneau** [Microsoft/VS-ColorThemes#63]
![theme-error](https://user-images.githubusercontent.com/945168/52989638-57298b80-33d2-11e9-9524-a32cf9c73ed9.jpg)

I realize these things take time to get updated, but I didn't see an issue yet. The plugin is currently incompatible with the latest preview.

**Comment by Invertex** [comment]
Just upgraded from 2017 and ran into this error as well. Happens when trying to load saved themes as well and have even managed to lock up and crash VS when trying to switch themes. Oddly enough it seems to still be able to switch the themes for the most part despite throwing an error each time.

**Comment by Invertex** [comment]
Fixed the issue, and this should be a simple fix for them too. 
ColorThemeEditor.dll just needs to be recompiled with reference to Microsoft.VisualStudio.ExtensionManager and .ExtensionEngine changed from 15.0.0.0 to 16.0.0.0, as it appears these two DLLs had a major version change between preview 2 and 3, and thus 15.0.0.0 no longer exists.

As a temporary workaround for anyone on preview 3, you can extract the ColorThemeEditor.vsix, as it's a ZIP file, and then modify those two reference's versions in the ColorThemeEditor.dll and then ZIP the files back up, rename extension to .vsix and install that. (I'd provide the modified file but I'm not sure if that part of this plugin is open source, as the code is not in this repo).

Works perfectly fine after making that simple change.

**Comment by prnadago** [comment]
Hey Invertex - your fix is valid. We're working on updating the extensions in the marketplace. Stay tuned for a new extension for VS 2019 that references the later version of ExtensionManager.

**Comment by EdCharbeneau** [comment]
I'm closing this issue because it looks to me like it has been resolved. Please re-open if necessary https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.VisualStudio2019ColorThemeEditor
