### ISSUE TITLE
Cannaot install it

### ISSUE THREAD

**Issue by JerzyR** [microsoft/VS-ColorThemes#66]
The VS 2019 option in installed is grayed out with message
The extension cannot be installed to this product due to prerequisites that cannot be resolved.
So, ok, what prerequisites this extension requires and where to get them please.
Thank you

**Comment by JerzyR** [comment]
Update I was able to install different package for Vs19, but also have an issue with Vs17
Nowhere to find how to open themes editor. The Customize Colors button under Tools menu is not installed/visible

**Comment by prnadago** [comment]
The extension has been updated on the Visual Studio marketplace. You can install it now :)
