### ISSUE TITLE
Cannot install on Visual Studio 2019

### ISSUE THREAD

**Issue by franzalex** [microsoft/VS-ColorThemes#67]
I have tried to install this extension by using the .VSIX and also from the extensions menu in Visual Studio 2019. In all cases the installation fails with the following exception:

 > This extension cannot be installed because the following references are missing:
 > - Microsoft.VisualStudio.Component.CoreEditor 

Surprisingly, the full-fledged [Color Theme Editor](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.VisualStudio2019ColorThemeEditor) extension installs with no issues.

Attached to this issue is the log from the last failed installation.

[dd_VSIXInstaller_20190404131539_2d50.log](https://github.com/Microsoft/VS-ColorThemes/files/3043640/dd_VSIXInstaller_20190404131539_2d50.log)

**Comment by cjbush** [comment]
I had the same issue with VS2019 Professional.

**Comment by BabyToy** [comment]
My solution to this was to clone the repository, and rebuild as a release.  
Install the built .vsix file and it should run without issues.

**Comment by Rod-Sychev** [comment]
I got the same issue with the VS 2019 Enterprise Version 16.0.1

**Comment by MarsonShine** [comment]
I have the same issue
vs2019 enterprise v16.0.1

**Comment by artasom** [comment]
In the code in the repository the manifest states
`<Prerequisites>
        <Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[15.0,)" DisplayName="Visual Studio core editor" />
    </Prerequisites>`
but in the extension in the marketplace the requirements are 
`Version="[16.0,17.0)"`
One option is to download the vsix file from the marketplace and to modify the manifest.json file so the requirements are `Version="[15.0,)"`.

**Comment by EP01** [comment]
I think all that's required here is to build a quick release and publish. Perhaps one of the MS contributors can do this for us? @madskristensen @ralmsdeveloper @prnadago

**Comment by voronoipotato** [comment]
Well it's pretty good that this is open source so that we can just build it and run it ourselves. Can you imagine if we didn't even have color themes on visual studio. Having to go through 300 different colors like cavemen.

**Comment by justcla** [comment]
> Well it's pretty good that this is open source so that we can just build it and run it ourselves.

Thanks. That was the idea. :-)

**Comment by voronoipotato** [comment]
The only thing this project needs is a vscode -> vs theme translator.

**Comment by prnadago** [comment]
Updated on the marketplace. Sorry that took so long :)
