### ISSUE TITLE
Solarized Dark theme issues with CSHTML files

### ISSUE THREAD

**Issue by justcla** [Microsoft/VS-ColorThemes#7]
Customer raised issue on Marketplace Q&A.

> Steven Salat on 13-Oct-2017 commented: 
> I found another problem with Solarized Dark theme in cshtml files. The C# code is highlighed in gray.
> 
> https://i.imgur.com/KPDJyhW.png

**Comment by styfle** [comment]
Duplicate of #6

**Comment by justcla** [comment]
Closing duplicate issue.
