### ISSUE TITLE
Doesn't work with Windows 10 high contrast theme.

### ISSUE THREAD

**Issue by behealed** [microsoft/VS-ColorThemes#81]
If you set Windows 10 to High Contrast theme, then the Color Theme dropdown box inside VS2019 (under Environment->General) is greyed out and cannot be changed. Likewise, the "apply" button found in this tool, is also greyed out and you cannot apply any color theme using this tool. And visual studio will appear all in black and white, and all your source code will be in white colored text only, which makes it slow and much more difficult to read your code. You lose all the colorization of your source code. If you know how to edit the registry, it is possible to copy all the values from the dark theme into the high contrast theme (overwriting visual studio's high contrast theme), thus forcing visual studio to use the dark theme. There is a tutorial that can be found on google, which worked on VS2017, explaining how to do this. But editing the registry by hand is very advanced and dangerous. Also, every time you install any update to visual studio, it overwrites any edits you made to the registry, which means you have to do the registry hack all over again to get the colors fixed. That's a huge pain in the butt. There is no reason why visual studio shouldn't allow users of the high contrast windows theme to edit the color theme inside visual studio. The very fact that we can hack the registry to forcibly fix the problem, shows that there is no technical reason why visual studio can't use its "dark" theme when windows is set to high contrast theme. It CAN be done through registry hacking, so WHY can't it simply be done under Environment->General? Why does visual studio disable the option to switch the color theme? WHY? This problem existed in VS2017 and was reported as a bug many times by many people, but it was never fixed during the years that we had VS2017. And now we're on VS2019 and the problem still exists. Will it ever be fixed? I downloaded this color themes editor tool hoping it would allow me to edit the theme, but all its "apply" buttons are also greyed out. But even though this tool doesn't work, it can still be done through registry hacking, but it's such a pain in the butt. I'm writing this issue report to help bring attention to this problem. If you don't believe me, simply go to Windows' theme editor (under Settings->Vision->High Contrast) and turn window's high contrast ON. Then, go to visual studio and you'll see that it will not allow you to edit the color theme, and all your source code will be white colored text and very ugly.

**Comment by Newrad0603** [comment]
This is just a set of themes for use in Visual Studio. VS controls what themes are visible and when based on registration and the Windows high contrast setting. There is a ticket tracking this feedback here:
https://developercommunity.visualstudio.com/idea/527413/visual-studio-forces-the-user-to-use-its-high-cont.html

I recommend following that to stay up to date on how that issue evolves.
