### ISSUE TITLE
Themes not applies to all parts of VS

### ISSUE THREAD

**Issue by MichaelMankiewicz** [microsoft/VS-ColorThemes#93]
Visual Studio 2019 Community Edition. When I use "Place tabs on the left" mode for opened documents, tabs bar has white background, so, captions are unreadable in dark themes. Scroll bar's arrows in "map mode"mode are white.

**Comment by Newrad0603** [comment]
These themes are not managed directly by VS like the core themes are. These are meant to be maintained and added to by the community, so please feel free to contribute updates to the themes as appropriate :)

Here's a list of the current color tokens likely missing from these themes for VS 2019:
    <Category Name="ACDCOverview" GUID="{c8887ac6-3c60-4209-9d69-8f4c12a60044}">
      <Color Name="Chevron" />
    </Category>
    <Category Name="Environment" GUID="{624ed9c3-bdfd-41fa-96c3-7c824ea32e3d}">
      <Color Name="ClassDesignerPrimaryGrabHandle" />
      <Color Name="ClassDesignerPrimaryLineGrabHandle" />
      <Color Name="ClassDesignerSecondaryLineGrabHandle" />
      <Color Name="CommandBarFrameControlHover" />
      <Color Name="CompletionBorder" />
      <Color Name="MainWindowSolutionNameActiveBackground" />
      <Color Name="MainWindowSolutionNameInactiveBackground" />
      <Color Name="MainWindowSolutionNameActiveText" />
      <Color Name="MainWindowSolutionNameInactiveText" />
      <Color Name="FileTabPrimarySeparator" />
      <Color Name="FileTabSecondarySeparator" />
      <Color Name="FileTabIndicatorTextSelectedActive" />
      <Color Name="FileTabIndicatorTextSelectedInactive" />
      <Color Name="FileTabScrollBarThumb" />
      <Color Name="FileTabScrollBarArrowGlyph" />
      <Color Name="FileTabScrollBarThumbHover" />
      <Color Name="FileTabScrollBarArrowGlyphHover" />
      <Color Name="FileTabScrollBarThumbPressed" />
      <Color Name="FileTabScrollBarArrowGlyphPressed" />
      <Color Name="MainWindowCloudEnvironmentActive" />
      <Color Name="MainWindowCloudEnvironmentInactive" />
      <Color Name="Halo" />
      <Color Name="FileTabParentText" />
      <Color Name="FileTabGroupTitleBackground" />
      <Color Name="FileTabActiveGroupTitleBackground" />
      <Color Name="FileTabActiveGroupBackground" />
      <Color Name="ToolWindowValidationErrorBorder" />
      <Color Name="ToolWindowValidationErrorText" />
    </Category>
    <Category Name="InformationBadge" GUID="{63f9718c-889b-4814-a3b4-6e81d14f1156}">
      <Color Name="Background" />
      <Color Name="Text" />
      <Color Name="BackgroundHover" />
      <Color Name="TextHover" />
      <Color Name="BackgroundPressed" />
      <Color Name="TextPressed" />
      <Color Name="BackgroundFocused" />
      <Color Name="TextFocused" />
      <Color Name="BackgroundDisabled" />
      <Color Name="TextDisabled" />
    </Category>
    <Category Name="ListViewGrid" GUID="{63dec435-18e1-4e62-a9a9-0495fcb524a3}">
      <Color Name="Border" />
      <Color Name="GridLines" />
      <Color Name="SelectedCellBorder" />
    </Category>
    <Category Name="Promotion" GUID="{8fafb063-4106-4756-81dc-d7769f24d056}">
      <Color Name="LightboxBackgroundOverlay" />
      <Color Name="LightboxDialogBackgroundPanel" />
      <Color Name="LightboxDialogPanelBodyText" />
      <Color Name="LightboxDialogPanelBorder" />
      <Color Name="LightboxDialogButton" />
      <Color Name="LightboxDialogButtonBorder" />
      <Color Name="LightboxDialogButtonPressed" />
      <Color Name="LightboxDialogButtonBorderPressed" />
      <Color Name="LightboxDialogButtonHover" />
      <Color Name="LightboxDialogButtonBorderHover" />
      <Color Name="LightboxDialogButtonFocused" />
      <Color Name="LightboxDialogButtonBorderFocused" />
      <Color Name="LightboxDialogButtonDisabled" />
      <Color Name="LightboxDialogButtonBorderDisabled" />
      <Color Name="LightboxDialogHeadline" />
      <Color Name="LightboxDialogHeading" />
      <Color Name="LightboxDialogCloseButtonGlyph" />
      <Color Name="LightboxDialogCloseButtonGlyphHover" />
      <Color Name="LightboxDialogCloseButtonGlyphFocused" />
    </Category>
    <Category Name="ThemedDialog" GUID="{5e04b2a9-e443-48db-8791-63a2a71cfbd7}">
      <Color Name="ListBox" />
      <Color Name="ListBoxBorder" />
      <Color Name="ListBoxDisabled" />
      <Color Name="ListBoxDisabledBorder" />
      <Color Name="TagText" />
      <Color Name="TagBorder" />
      <Color Name="TagBackground" />
      <Color Name="PromotionBoxBackground" />
      <Color Name="PromotionBoxBorder" />
      <Color Name="PromotionBoxText" />
      <Color Name="ValidationError" />
      <Color Name="ValidationErrorText" />
      <Color Name="ActionButtonBackground" />
      <Color Name="ActionButtonStroke" />
      <Color Name="ActionButtonStrokeHover" />
      <Color Name="ActionButtonStrokeActive" />
      <Color Name="ActionButtonText" />
      <Color Name="ActionButtonTextActive" />
      <Color Name="StartWindowDescription" />
      <Color Name="StartWindowDescriptionActive" />
      <Color Name="StartWindowDescriptionHover" />
      <Color Name="CloseWindowButtonHover" />
      <Color Name="TemplateNewTag" />
      <Color Name="TemplateNewTagSelected" />
    </Category>
    <Category Name="ThemedUtilityDialog" GUID="{e2961a72-48a5-4da7-8168-1fee490f78a7}">
      <Color Name="ActiveCaption" />
      <Color Name="WindowBorder" />
      <Color Name="WindowPanel" />
      <Color Name="WindowButton" />
      <Color Name="WindowButtonHover" />
      <Color Name="WindowButtonDown" />
      <Color Name="WindowButtonBorder" />
      <Color Name="WindowButtonHoverBorder" />
      <Color Name="WindowButtonDownBorder" />
      <Color Name="WindowButtonGlyph" />
      <Color Name="WindowButtonDownGlyph" />
      <Color Name="WindowButtonHoverGlyph" />
    </Category>
    <Category Name="UnthemedDialog" GUID="{d1fae935-144d-45a6-af9a-d615e3cd7b75}">
      <Color Name="Hyperlink" />
      <Color Name="HyperlinkHover" />
      <Color Name="HyperlinkPressed" />
    </Category>
    <Category Name="UserInformation" GUID="{b6d9f1fc-e422-4755-a014-3fb666d831dc}">
      <Color Name="IDCardMinimalModeText" />
      <Color Name="IDCardMinimalModeInactiveWindowText" />
      <Color Name="IDCardMinimalModeInactiveText" />
      <Color Name="IDCardMinimalModeInactiveWindowInactiveText" />
    </Category>
    <Category Name="UserNotifications" GUID="{5d42b198-efca-431c-92aa-8b595d0d39c2}">
      <Color Name="ToastPanelBackground" />
      <Color Name="ToastTitleText" />
      <Color Name="ToastMessageText" />
      <Color Name="ToastPanelBorder" />
      <Color Name="ToastGlyphButton" />
      <Color Name="ToastGlyphButtonHover" />
      <Color Name="ToastGlyphButtonPressed" />
      <Color Name="ToastActionButton" />
      <Color Name="ToastActionButtonBorder" />
      <Color Name="ToastActionButtonText" />
      <Color Name="ToastActionButtonHover" />
      <Color Name="ToastActionButtonBorderHover" />
      <Color Name="ToastActionButtonTextHover" />
      <Color Name="ToastActionButtonPressed" />
      <Color Name="ToastActionButtonBorderPressed" />
      <Color Name="ToastActionButtonDisabled" />
      <Color Name="ToastActionButtonBorderDisabled" />
      <Color Name="ToastActionButtonTextDisabled" />
      <Color Name="ToastActionButtonTextPressed" />
      <Color Name="IndicatorBubble" />
      <Color Name="IndicatorBubbleDebugging" />
    </Category>
    <Category Name="VisualStudioInstaller" GUID="{53212856-7528-403d-84e6-76820f4cef73}">
      <Color Name="Background" />
      <Color Name="Border" />
      <Color Name="HeaderTextBrand" />
      <Color Name="PivotText" />
      <Color Name="PivotBar" />
      <Color Name="SectionDivider" />
      <Color Name="HeaderText" />
      <Color Name="SectionHeaderText" />
      <Color Name="SupportText" />
      <Color Name="BodyText" />
      <Color Name="Hyperlink" />
      <Color Name="HyperlinkHover" />
      <Color Name="HyperlinkPressed" />
    </Category>
    <Category Name="VSSearch" GUID="{04ba5a31-6d4d-4225-9194-2e38a9175e31}">
      <Color Name="TabSelectionActive" />
      <Color Name="WindowPanelText" />
      <Color Name="WindowPanelTabDivider" />
      <Color Name="WindowPanelSupportText" />
      <Color Name="WindowPanelBorder" />
      <Color Name="WindowPanel" />
      <Color Name="ListItemBackgroundHover" />
      <Color Name="ListItemBorderHover" />
      <Color Name="ListItemSupportTextHover" />
    </Category>
